### ISSUE TITLE
How to access and/or modify graphics within the R6 object

### ISSUE THREAD

**Issue by brianmsm** [silkyproject/silkyR#324]
I'm not sure if this would be the right place for this. I was wondering what would be the way to be able to modify a chart that is generated with some function of the `jmv` package. For example, modify general chart colors or use `ggsave` to control export parameters from R.

``` r
results <- jmv::descriptives(
  data = mtcars,
  vars = vars(mpg, cyl, disp),
  hist = TRUE)

plots <- results$plots

plots
```

![](https://i.imgur.com/4K5pZ5u.png)![](https://i.imgur.com/NFJT0UM.png)![](https://i.imgur.com/ehbF66r.png)

<sup>Created on 2021-11-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by jonathon-love** [comment]
i think using your example, you can get a ggplot object as follows:

```
ggplotobject <- plots[[1]]$items$hist$plot$fun()
```

cheers

**Comment by brianmsm** [comment]
Great! That's what I wanted. Thank you very much!

I will close this issue.
