### ISSUE TITLE
Non-unicode alternative for Greek letters

### ISSUE THREAD

**Issue by tsrobinson** [silkyproject/silkyR#340]
Hi there, I use your package when teaching undergraduates statistics and students really love the clarity of the output.

I'm running into a few issues where students with system language settings other than English get multibyte string errors when R tries to render the Greek letters in the output headings (using RStudio). 

For example, when running `contTables()`, it seems to fail rendering the chi-2 heading:

`Error in withCallingHandlers(expr, warning = function (w)... invalid multibyte string at '<cf><87><c2>?Tests'`

I was wondering if in a future update it would be possible to have a non-unicode alternative for these headings, based on detecting a user's system language?

Thanks!

**Comment by jonathon-love** [comment]
hmm, let me take a look. we may be able to address this.

but basically, we're all waiting for R 4.2 to come out to fix these issues once and for all:

https://developer.r-project.org/Blog/public/2021/12/07/upcoming-changes-in-r-4.2-on-windows/

jonathon

**Comment by tsrobinson** [comment]
Thanks Jonathon!

**Comment by jonathon-love** [comment]
i think this may longer be an issue since R 4.2 ...

**Comment by jonathon-love** [comment]
i think this is all fixed in R 4.2+
