### ISSUE TITLE
Running a code in jmv package causes fatal error

### ISSUE THREAD

**Issue by mrorangutann** [silkyproject/silkyR#349]
jmv::anovaOneW(
  formula = hp ~ gear,
  data = mtcars)

Running even simple code like this causes R to throw a fatal error.  I don't have the slightest idea why.
![0d2fe95e3a8c38e3e14699d94e7c26c6630b0310](https://user-images.githubusercontent.com/90481887/173599444-9bdfc255-d5cf-4d0f-a33a-5c6effcd089c.png)

**Comment by jonathon-love** [comment]
yeah, that's peculiar ... i'm not having an trouble with that analysis here. what OS are you running?, what version R?, is your jmv and jmvcore up to date?, etc.

**Comment by paulwarren** [comment]
I'm getting this too. R version 4.2.0 in RStudio 2022.02.03.492. Downloaded the jmv and jmvcore packages today, so I am assuming they are the most recent. However, I CAN run Jamovi in R (i.e. not RStudio), so this looks like a jmv/RStudio conflict

**Comment by Hallo951** [comment]
I get the same error with the same combination of R and R-studio...

**Comment by jonathon-love** [comment]
hi, looks like an rstudio problem. update your rstudio and i think you'll find its not longer a problem.

cheers

**Comment by mrorangutann** [comment]
hi community ı solved the problem. ı changed  r studio to this https://cran.r-project.org/bin/windows/base/rpatched.html and this fixed all my problem
