### ISSUE TITLE
Duplicate code in test in testttestis.R

### ISSUE THREAD

**Issue by karchjd** [silkyproject/silkyR#376]
The test 'Error is thrown if grouping var has more than 2 levels' is twice in the file.

**Comment by jonathon-love** [comment]
we are getting all passes on our unit tests here ...

<img width="684" alt="Screenshot 2023-02-22 at 10 03 11" src="https://user-images.githubusercontent.com/3240247/220478559-fbe9b5ac-69bc-4f4e-a0e5-b5bbc30f2c6d.png">

**Comment by karchjd** [comment]
It seems like I should have been more specific. Have a look at lines 90 to 116:

```
testthat::test_that('Error is thrown if grouping var has more than 2 levels', {
    df <- data.frame(
        dep = c(1, 7, 4),
        group = c("a", "b", "c"),
        stringsAsFactors = TRUE
    )

    testthat::expect_error(
        jmv::ttestIS(df, vars = "dep", group = "group"),
        "Grouping variable 'group' must have exactly 2 levels",
        fixed=TRUE
    )
})

testthat::test_that('Error is thrown if grouping var has more than 2 levels', {
    df <- data.frame(
        dep = c(1, 7, 4),
        group = c("a", "b", "c"),
        stringsAsFactors = TRUE
    )

    testthat::expect_error(
        jmv::ttestIS(df, vars = "dep", group = "group"),
        "Grouping variable 'group' must have exactly 2 levels",
        fixed=TRUE
    )
})
```
The unit tests contain exactly the same test twice. Not really a problem but just wanted to let you know,

**Comment by raviselker** [comment]
Well, that took us a lot longer to fix than necessary 😛. Thank you for reporting this though!
