### ISSUE TITLE
jmv breaks purrr and/or arrow when loaded 

### ISSUE THREAD

**Issue by ghost** [silkyproject/silkyR#388]
Hello.

Loading this package before and after packages such as purrr and arrow will cause functions using them both to break and gives this error: 

```
Error in `pmap()`:
ℹ In index: 1.
Caused by error in `!column$visible`:
! invalid argument type`
```
Not sure what is causing this problem, when rlang::trace() is ran this log is given: 
```
3. ├─purrr::pmap_dfr(...)
4. │ └─purrr::pmap(.l, .f, ...)
...
 13. ├─dplyr::collect(.)
 14. └─arrow:::collect.arrow_dplyr_query(.)
 15.   └─arrow:::collect.ArrowTabular(out, as_data_frame)
 16.     ├─base::as.data.frame(x, ...)
 17.     └─jmvcore:::as.data.frame.Table(x, ...)
```
It seems to happen in particular when a `collect()` is called inside a `map` function  

Any advice in dealing with this would be much appreciated :)

**Comment by jonathon-love** [comment]
hi,

it might be worth touching base with the `purrr` and `arrow` folks ... as i don't think we're doing anything we shouldn't.

cheers

**Comment by jonathon-love** [comment]
it looks like a collision between `S3` classes ... it looks as though both projects might have elected to name their classes too generically ... both settling on the name `Table` ... but i think they'll be able to work around this.
