### ISSUE TITLE
Using moretests module in R’s jmv package

### ISSUE THREAD

**Issue by ymjang71** [silkyproject/silkyR#414]
I installed jonathon-love/moretests along with jmv package to run moretests in R setting. But it doesn’t seem to activate. Is it impossible to use jamovi modules in R’s jmv package?

**Comment by jonathon-love** [comment]
yeah, i don't think you can use `moretests` from R sorry.

**Comment by ymjang71** [comment]
Hey! Thanks for quick response 👍
